[2024-03-10T10:25:29.352+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task2dag.delete_csv manual__2024-03-10T10:23:11.469628+00:00 [queued]>
[2024-03-10T10:25:29.371+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task2dag.delete_csv manual__2024-03-10T10:23:11.469628+00:00 [queued]>
[2024-03-10T10:25:29.373+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-10T10:25:29.402+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): delete_csv> on 2024-03-10 10:23:11.469628+00:00
[2024-03-10T10:25:29.417+0000] {standard_task_runner.py:60} INFO - Started process 2693 to run task
[2024-03-10T10:25:29.423+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'task2dag', 'delete_csv', 'manual__2024-03-10T10:23:11.469628+00:00', '--job-id', '875', '--raw', '--subdir', 'DAGS_FOLDER/task2dag.py', '--cfg-path', '/tmp/tmpcdpmimxg']
[2024-03-10T10:25:29.426+0000] {standard_task_runner.py:88} INFO - Job 875: Subtask delete_csv
[2024-03-10T10:25:29.507+0000] {task_command.py:423} INFO - Running <TaskInstance: task2dag.delete_csv manual__2024-03-10T10:23:11.469628+00:00 [running]> on host 9268fe474086
[2024-03-10T10:25:29.667+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='task2dag' AIRFLOW_CTX_TASK_ID='delete_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T10:23:11.469628+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T10:23:11.469628+00:00'
[2024-03-10T10:25:29.671+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-10T10:25:29.675+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'rm-r extracted_data/']
[2024-03-10T10:25:29.716+0000] {subprocess.py:86} INFO - Output:
[2024-03-10T10:25:29.737+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: rm-r: command not found
[2024-03-10T10:25:29.739+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-03-10T10:25:29.758+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-10T10:25:29.767+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=task2dag, task_id=delete_csv, execution_date=20240310T102311, start_date=20240310T102529, end_date=20240310T102529
[2024-03-10T10:25:29.799+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 875 for task delete_csv (Bash command failed. The command returned a non-zero exit code 127.; 2693)
[2024-03-10T10:25:29.836+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-10T10:25:29.873+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
