[2024-03-09T22:27:35.273+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task2dag.delete_csv manual__2024-03-09T22:21:13.686079+00:00 [queued]>
[2024-03-09T22:27:35.282+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task2dag.delete_csv manual__2024-03-09T22:21:13.686079+00:00 [queued]>
[2024-03-09T22:27:35.283+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-03-09T22:27:35.297+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): delete_csv> on 2024-03-09 22:21:13.686079+00:00
[2024-03-09T22:27:35.308+0000] {standard_task_runner.py:60} INFO - Started process 1930 to run task
[2024-03-09T22:27:35.311+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'task2dag', 'delete_csv', 'manual__2024-03-09T22:21:13.686079+00:00', '--job-id', '867', '--raw', '--subdir', 'DAGS_FOLDER/task2dag.py', '--cfg-path', '/tmp/tmp3cy4yylh']
[2024-03-09T22:27:35.312+0000] {standard_task_runner.py:88} INFO - Job 867: Subtask delete_csv
[2024-03-09T22:27:35.356+0000] {task_command.py:423} INFO - Running <TaskInstance: task2dag.delete_csv manual__2024-03-09T22:21:13.686079+00:00 [running]> on host 9268fe474086
[2024-03-09T22:27:35.428+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='task2dag' AIRFLOW_CTX_TASK_ID='delete_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T22:21:13.686079+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-09T22:21:13.686079+00:00'
[2024-03-09T22:27:35.430+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-09T22:27:35.432+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'rm-r extracted_data/']
[2024-03-09T22:27:35.452+0000] {subprocess.py:86} INFO - Output:
[2024-03-09T22:27:35.454+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: rm-r: command not found
[2024-03-09T22:27:35.455+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-03-09T22:27:35.465+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-09T22:27:35.469+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=task2dag, task_id=delete_csv, execution_date=20240309T222113, start_date=20240309T222735, end_date=20240309T222735
[2024-03-09T22:27:35.481+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 867 for task delete_csv (Bash command failed. The command returned a non-zero exit code 127.; 1930)
[2024-03-09T22:27:35.523+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-09T22:27:35.542+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
