[2024-03-09T20:25:29.722+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task1dag.archive_data manual__2024-03-09T20:20:37.215618+00:00 [queued]>
[2024-03-09T20:25:29.731+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task1dag.archive_data manual__2024-03-09T20:20:37.215618+00:00 [queued]>
[2024-03-09T20:25:29.732+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-09T20:25:29.744+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): archive_data> on 2024-03-09 20:20:37.215618+00:00
[2024-03-09T20:25:29.751+0000] {standard_task_runner.py:60} INFO - Started process 729 to run task
[2024-03-09T20:25:29.754+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'task1dag', 'archive_data', 'manual__2024-03-09T20:20:37.215618+00:00', '--job-id', '647', '--raw', '--subdir', 'DAGS_FOLDER/task1dag.py', '--cfg-path', '/tmp/tmpor26t8bd']
[2024-03-09T20:25:29.756+0000] {standard_task_runner.py:88} INFO - Job 647: Subtask archive_data
[2024-03-09T20:25:29.793+0000] {task_command.py:423} INFO - Running <TaskInstance: task1dag.archive_data manual__2024-03-09T20:20:37.215618+00:00 [running]> on host 43465f8902fb
[2024-03-09T20:25:29.865+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='task1dag' AIRFLOW_CTX_TASK_ID='archive_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T20:20:37.215618+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-09T20:20:37.215618+00:00'
[2024-03-09T20:25:39.845+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-03-09T20:25:39.850+0000] {process_utils.py:131} INFO - Sending 15 to group 729. PIDs of all processes in the group: [729]
[2024-03-09T20:25:39.851+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 729
[2024-03-09T20:25:39.851+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-09T20:25:39.944+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=729, status='terminated', exitcode=0, started='20:25:28') (729) terminated with exit code 0
