[2024-03-02T18:31:17.127+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_1_dag.scrape_data_2018 manual__2024-03-02T18:31:13.949263+00:00 [queued]>
[2024-03-02T18:31:17.136+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_1_dag.scrape_data_2018 manual__2024-03-02T18:31:13.949263+00:00 [queued]>
[2024-03-02T18:31:17.137+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-02T18:31:17.152+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): scrape_data_2018> on 2024-03-02 18:31:13.949263+00:00
[2024-03-02T18:31:17.160+0000] {standard_task_runner.py:60} INFO - Started process 1773 to run task
[2024-03-02T18:31:17.162+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'task_1_dag', 'scrape_data_2018', 'manual__2024-03-02T18:31:13.949263+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/check2.py', '--cfg-path', '/tmp/tmpl0lywfvg']
[2024-03-02T18:31:17.166+0000] {standard_task_runner.py:88} INFO - Job 372: Subtask scrape_data_2018
[2024-03-02T18:31:17.214+0000] {task_command.py:423} INFO - Running <TaskInstance: task_1_dag.scrape_data_2018 manual__2024-03-02T18:31:13.949263+00:00 [running]> on host e8513bfd2c92
[2024-03-02T18:31:17.281+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='task_1_dag' AIRFLOW_CTX_TASK_ID='scrape_data_2018' AIRFLOW_CTX_EXECUTION_DATE='2024-03-02T18:31:13.949263+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-02T18:31:13.949263+00:00'
[2024-03-02T18:31:17.283+0000] {logging_mixin.py:188} INFO - cwd: /opt/***
[2024-03-02T18:39:01.949+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-03-02T18:39:01.954+0000] {process_utils.py:131} INFO - Sending 15 to group 1773. PIDs of all processes in the group: [1773]
[2024-03-02T18:39:01.954+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1773
[2024-03-02T18:39:01.955+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-02T18:39:02.007+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1773, status='terminated', exitcode=0, started='18:31:16') (1773) terminated with exit code 0
