[2024-03-09T20:41:09.411+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: task1dag.scrape_data_2012 manual__2024-03-09T20:26:55.548059+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
