[2024-03-09T20:46:26.517+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: task1dag.scrape_data_2012 scheduled__2024-03-08T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
